/*
 *  ======== config.h ========
 *  Configuration-specific definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */
#ifndef config_h
#define config_h 1

#include "INA229.h"

/* support C++ sources */
#ifdef __cplusplus
extern "C" {
#endif

// First set on SPI2 (busId = 0)
extern const INA229_Handle INA229_0;
extern const INA229_Handle INA229_1;
extern const INA229_Handle INA229_2;
extern const INA229_Handle INA229_3;
extern const INA229_Handle INA229_4;
extern const INA229_Handle INA229_5;
extern const INA229_Handle INA229_6;
extern const INA229_Handle INA229_7;
extern const INA229_Handle INA229_8;
extern const INA229_Handle INA229_9;
extern const INA229_Handle INA229_10;
extern const INA229_Handle INA229_11;
extern const INA229_Handle INA229_12;

// Second set on SPI1 (busId = 1)
extern const INA229_Handle INA229_13;
extern const INA229_Handle INA229_14;
extern const INA229_Handle INA229_15;
extern const INA229_Handle INA229_16;
extern const INA229_Handle INA229_17;
extern const INA229_Handle INA229_18;
extern const INA229_Handle INA229_19;
extern const INA229_Handle INA229_20;
extern const INA229_Handle INA229_21;
extern const INA229_Handle INA229_22;
extern const INA229_Handle INA229_23;
extern const INA229_Handle INA229_24;
extern const INA229_Handle INA229_25;

#ifdef __cplusplus
}
#endif  /* C++ support end */

#endif  /* include guard */
