/*
 *  ======== config.h ========
 *  Configuration-specific definitions
 *
 *  DO NOT EDIT - This file is generated by the SysConfig tool for
 *  the TI Sensors in this application.
 */
#ifndef config_h
#define config_h 1

#include "INA229.h"

/* support C++ sources */
#ifdef __cplusplus
extern "C" {
#endif

extern const INA229_Handle INA229_0;
extern const INA229_Handle INA229_1;
extern const INA229_Handle INA229_2;
extern const INA229_Handle INA229_3;
extern const INA229_Handle INA229_4;
extern const INA229_Handle INA229_5;
extern const INA229_Handle INA229_6;
extern const INA229_Handle INA229_7;
extern const INA229_Handle INA229_8;
extern const INA229_Handle INA229_9;
extern const INA229_Handle INA229_10;
extern const INA229_Handle INA229_11;
extern const INA229_Handle INA229_12;

#ifdef __cplusplus
}
#endif  /* C++ support end */

#endif  /* include guard */
